trigger:
- main
pool:
 vmImage: 'unbuntu-latest'
 name: Default

variables:
 buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'